# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(419, 575)
        Settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.minutes = QtWidgets.QGroupBox(Settings)
        self.minutes.setTitle("")
        self.minutes.setObjectName("minutes")
        self.formLayout = QtWidgets.QFormLayout(self.minutes)
        self.formLayout.setObjectName("formLayout")
        self.stateTomatoLabel = QtWidgets.QLabel(self.minutes)
        self.stateTomatoLabel.setObjectName("stateTomatoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stateTomatoLabel)
        self.stateTomato = QtWidgets.QSpinBox(self.minutes)
        self.stateTomato.setMinimum(1)
        self.stateTomato.setObjectName("stateTomato")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stateTomato)
        self.stateBreakLabel = QtWidgets.QLabel(self.minutes)
        self.stateBreakLabel.setObjectName("stateBreakLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stateBreakLabel)
        self.stateBreak = QtWidgets.QSpinBox(self.minutes)
        self.stateBreak.setMinimum(1)
        self.stateBreak.setObjectName("stateBreak")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stateBreak)
        self.stateLongBreakLabel = QtWidgets.QLabel(self.minutes)
        self.stateLongBreakLabel.setObjectName("stateLongBreakLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stateLongBreakLabel)
        self.stateLongBreak = QtWidgets.QSpinBox(self.minutes)
        self.stateLongBreak.setMinimum(1)
        self.stateLongBreak.setObjectName("stateLongBreak")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.stateLongBreak)
        self.repeatLabel = QtWidgets.QLabel(self.minutes)
        self.repeatLabel.setObjectName("repeatLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.repeatLabel)
        self.repeat = QtWidgets.QSpinBox(self.minutes)
        self.repeat.setMinimum(1)
        self.repeat.setObjectName("repeat")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.repeat)
        self.verticalLayout.addWidget(self.minutes)
        self.checkboxes = QtWidgets.QGroupBox(Settings)
        self.checkboxes.setTitle("")
        self.checkboxes.setObjectName("checkboxes")
        self.formLayout_2 = QtWidgets.QFormLayout(self.checkboxes)
        self.formLayout_2.setObjectName("formLayout_2")
        self.notification = QtWidgets.QCheckBox(self.checkboxes)
        self.notification.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.notification.setAutoRepeat(False)
        self.notification.setAutoExclusive(False)
        self.notification.setTristate(False)
        self.notification.setObjectName("notification")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.notification)
        self.interrupt = QtWidgets.QCheckBox(self.checkboxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interrupt.sizePolicy().hasHeightForWidth())
        self.interrupt.setSizePolicy(sizePolicy)
        self.interrupt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.interrupt.setAutoFillBackground(False)
        self.interrupt.setObjectName("interrupt")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.interrupt)
        self.autoStopTomato = QtWidgets.QCheckBox(self.checkboxes)
        self.autoStopTomato.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.autoStopTomato.setObjectName("autoStopTomato")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.autoStopTomato)
        self.autoStopBreak = QtWidgets.QCheckBox(self.checkboxes)
        self.autoStopBreak.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.autoStopBreak.setObjectName("autoStopBreak")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.autoStopBreak)
        self.switchToTomatoOnAbort = QtWidgets.QCheckBox(self.checkboxes)
        self.switchToTomatoOnAbort.setMinimumSize(QtCore.QSize(0, 0))
        self.switchToTomatoOnAbort.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.switchToTomatoOnAbort.setObjectName("switchToTomatoOnAbort")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.switchToTomatoOnAbort)
        self.verticalLayout.addWidget(self.checkboxes)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.stateTomatoLabel.setText(_translate("Settings", "Tomato time (min)"))
        self.stateBreakLabel.setText(_translate("Settings", "Break time (min)"))
        self.stateLongBreakLabel.setText(_translate("Settings", "Long break time (min)"))
        self.repeatLabel.setText(_translate("Settings", "Long break after (tomatoes)"))
        self.notification.setText(_translate("Settings", "Sound notification"))
        self.interrupt.setText(_translate("Settings", "Interrupt me"))
        self.autoStopTomato.setText(_translate("Settings", "Auto stop tomato after break"))
        self.autoStopBreak.setText(_translate("Settings", "Auto stop break after tomato"))
        self.switchToTomatoOnAbort.setText(_translate("Settings", "Skip break if you press stop button"))
